# Generated by Django 5.2.7 on 2025-12-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Viraj & Dhaval'", max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('short_message', models.TextField(blank=True, help_text='Highlight quote (1–2 lines).')),
                ('full_message', models.TextField(blank=True, help_text='Full testimonial/story.')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
