# Generated by Django 5.2.7 on 2025-10-26 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('proofing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.photo'),
        ),
        migrations.AddField(
            model_name='proofinggallery',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proofinggallery',
            name='photos',
            field=models.ManyToManyField(blank=True, to='portfolio.photo'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='proofing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='proofing.proofinggallery'),
        ),
    ]
