# Generated by Django 5.2.7 on 2025-11-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='invited_emails',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='password',
        ),
        migrations.AddField(
            model_name='gallery',
            name='background_music',
            field=models.FileField(blank=True, help_text='Upload an MP3 file to play as background music', null=True, upload_to='gallery_music/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_covers/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, help_text='Short story about this couple or event'),
        ),
    ]
